name: "Sample Private Composite Action"
description: "Authenticates to a docker registry and executes the docker image"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true

runs:
  using: "composite"
  steps:
     - name: Checkout Code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - uses: docker/login-action@v1
       with:
         username: ${{inputs.registry_username}}
         password: ${{inputs.registry_password}}

     - name: Run Random Image
       uses: docker://chocrates/comicbox:latest
