name: "Sample Private Composite Action"
description: "Authenticates to a docker registry and executes the docker image"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true

runs:
  using: "composite"
  steps:
     - name: Checkout Code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0

     - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}

     - name: Lint Code Base
       uses: docker://ghcr.io/github/super-linter:latest
       env:
         ACTIONS_RUNNER_DEBUG: true
         ERROR_ON_MISSING_EXEC_BIT: true
         VALIDATE_ALL_CODEBASE: false
