name: "Sample Private Composite Action"
description: "Authenticates to a docker registry and executes the docker image"

inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true

runs:
  using: "composite"
  steps:
     - name: Pull Random Image
       run: docker pull chocrates/comicbox:latest
       shell: bash

     - name: Run Random Image
       run: docker run hello-world
       shell: bash
  
