name: Node CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
env:
  name: 'default'
  home: 'default'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - run: |
            echo "yes" \
            "no" \
            "maybe"
        - name: set env vars if workflow
          if: ${{ github.event.inputs.name }}
          run: |
            echo "name=${{ github.event.inputs.name }}" >> $GITHUB_ENV
            echo "home=${{ github.event.inputs.home }}" >> $GITHUB_ENV
        - run: |
            echo $name
            echo $home

  
