name: Python Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Secret obfuscation
        env:
          IAMASECRET: ${{ secrets.GITHUB_TOKEN }}
        run:  echo $IAMASECRET
