name: Python Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Secret obfuscation
        env:
          IAMASECRET: ${{ secrets.GITHUB_TOKEN }}
        run:  echo $IAMASECRET
