name: Python Sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Secret obfuscation
        env:
          IAMASECRET: ${{ secrets.SECRET }}
        run:  echo $IAMASECRET
