name: Show Secrets

on:
  workflow_dispatch:



jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Write Secrets to console
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/Chocrates/actions-samples
