name: Provision Resources With Terraform

on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan \
          -var='subsription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}' \
          -var='client_id=${{ secrets.AZURE_CLIENT_ID }}' \
          -var='client_secret=${{ secrets.AZURE_CLIENT_SECRET }}' \
          -var='tenant_id=${{ secrets.AZURE_TENANT_ID }}' \
          -var='resource_group_name=chocrates-rg'

      - name: Terraform Apply
        id: terraform
        working-directory: terraform
        run: terraform apply
