name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      TEST: "value"
    steps:
        - uses: actions/checkout@v2
        - id: first
          run: |
           VAR=$(git branch | head -n1)
           echo "::set-output name=git_status::$VAR"
        - id: test
          env: 
           STATUS: ${{ steps.first.outputs.git_status }}
          run: echo $STATUS
        - id: last
          uses: actions/checkout@v2
          with:
            one: "Front Bit ${{ env.test }} back bit"
