name: Context
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      repository: chocrates/tools
    - name: Generate Token
      id: generate-token
      run: |
        cd tools/generate-jwt-key
        npm install
        echo "${{ secrets.private_key }}" > private_key
        T=$(curl --silent -X POST -H "Authorization: Bearer $(node generate-jwt-key.js --private-key private_key --app-id $APP_ID)" -H "Accept: application/vnd.github.v3+json" https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens | jq '.token' | sed 's/"//g')
        echo "::set-output name=token::$T"
      env:
        APP_ID: 245037
        INSTALLATION_ID: 29960440
        
    - run: echo "${{ $steps.generate-token.outputs.token.value }}"
 
