name: Context
on:
  workflow_dispatch:
env:
  one: "TWO"

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      TEST: "value"
    steps:
    - name: View context attributes
      uses: actions/github-script@v5
      env:
        environment: "variables"
      with:
        test: "value"
        script: console.log(context)
