name: Azure WebApp Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "azure/"
      
jobs:
  changed-files:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      arm: ${{ steps.changes.outputs.all}}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=arm::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep azuredeploy | xargs)"

  deploy-arm:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{needs.changed-files.outputs.arm}}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: chocrates-webdeploy
        template: ./azure/azuredeploy.json
        parameters: ./azure/azuredeploy.parameters.json
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: deploy-arm
    steps:
      - uses: actions/checkout@v2
      - name: Set up dotnet Core ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      - name: Restore
        run: |
          cd <name of your app>
          dotnet restore
      - name: Build
        run: |
          cd <name of your app>
          dotnet build --no-restore
      - name: Publish
        run: |
          cd <name of your app>
          dotnet publish --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_NAME }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./published
