on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env'     
        required: true
        
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event.inputs.environment }}
    - name: Run dev seed
      env:
        var: 1
        var2: 2
      if: ${{ github.event.inputs.environment  == 'dev' }}
      run: |
        echo "export var=11"
           
    - name: Run test seed
      if: ${{ github.event.inputs.environment  == 'test' }}
      run: |
        env
  
